# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
#relative_permalinks: true

# Setup
title:               Sam Stephenson
tagline:             Designer
url:                 http://samstephenson.com
paginate:            1
baseurl:             ""

# Assets
gems:                [jekyll-paginate]


#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sam Stephenson
  url:               https://samstephenson.com
  email:             sam@stephenson.net

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
